# Site settings
title: Hyemin Bang
email: hbang@csail.mit.edu
description: > # this means to ignore newlines until "baseurl:"
   Student at MIT
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hhybang.github.io/" # the base hostname & protocol for your site
production_url: "https://hhybang.github.io/"
github_username: hhybang
permalink: /blog/:year/:month/:title.html


sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
